# This is a basic workflow to help you get started with Actions

name: Build-sphinx-docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install sphinx sphinx_rtd_theme
      # pip install -r requirements.txt
      - name: Build HTML
        run: |
          sphinx-build -b html docs dist-docs

      - name: Store docs HTML as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: dist-docs
  
  publish-docs:
    runs-on: ubuntu-latest
    needs: docs
    permissions:
      contents: write
    steps:
    - name: Download docs HTML from artifact storage
      uses: actions/download-artifact@v3
      with:
        name: docs
        path: dist-docs

    - name: Upload docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist-docs
